### ISSUE TITLE
PepBB model unzip

### ISSUE THREAD

**Issue by kimdn** [strauchlab/iNNterfaceDesign#1]
Manual ms word file says

![image](https://user-images.githubusercontent.com/3903446/155869103-70762875-a146-403f-9945-e93345b8e0e5.png)

--
However, my
unzip '*.zip' at centos
shows

```
Archive:  PepBB.zip
warning [PepBB.zip]:  zipfile claims to be last disk of a multi-part archive;
  attempting to process anyway, assuming all parts have been concatenated
  together in order.  Expect "errors" and warnings...true multi-part support
  doesn't exist yet (coming soon).
file #1:  bad zipfile offset (local header sig):  4

1 archive had fatal errors.

```

Double-clicking PepBB.zip, PepBB.z01, PepBB.z02 on my macOS led me one file only (e.g. PepBB.hdf5 that is ~220 MB). Is this PepBB.hdf5 the only one that is required?

**Comment by rsyrlyb** [comment]
Yes, it is correct. The result of the unzipping should be that one file
