### ISSUE TITLE
Issue of running 2.binders.py

### ISSUE THREAD

**Issue by yangche7** [strauchlab/iNNterfaceDesign#2]
Hello, 
I've tried to run the nice script you deposited, but encountered with an issue while using 2.binders.py. Of which the error I got: 

/home/anaconda3/envs/myenv_3.7/lib/python3.7/site-packages/keras/layers/core/lambda_layer.py:305: UserWarning: models_bb is not loaded, but a Lambda layer uses it. It may cause errors.
  'function_type')
Traceback (most recent call last):
  File "2.binders.py", line 193, in <module>
    pdb_names = make_binders(data, data2, keywords)
  File "2.binders.py", line 79, in make_binders
    model_pos = load_model(dir_models + 'Orn.hdf5')
  File "/home/anaconda3/envs/myenv_3.7/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/raulia/projects/backbone_all/models_bb.py", line 87, in <lambda>
NameError: Exception encountered when calling layer "lambda_2" (type Lambda).

name 'K' is not defined
______________________________________________________________________________________
do we need to somehow need to have this 'models_bb.py' file ? 
thanks for helping out here !

**Comment by rsyrlyb** [comment]
Hello, 
I edited file 2.binders.py a bit. Try to run it and let me know the result, please.

**Comment by yangche7** [comment]
Hello, 
it seems working well after your latest update. But I got another error that I will open another issue :)

**Comment by yangche7** [comment]
thanks ! great work !
