### ISSUE TITLE
1.preprocessing.py error

### ISSUE THREAD

**Issue by kimdn** [strauchlab/iNNterfaceDesign#3]
Thank you for sharing code.

I downloaded 3ztj.pdb

Then, modified it to start with resnum=1 by https://github.com/haddocking/pdb-tools

Then, I ran
`python ../iNNterfaceDesign_scripts/1.preprocessing.py PepBB.input`

Then, I see
<img width="796" alt="Screen Shot 2022-03-23 at 9 11 15 PM" src="https://user-images.githubusercontent.com/3903446/159840743-663150ed-c03a-443b-a06f-b62100ded8f8.png">

Can you upload your/working 3ztj.pdb file?

Maybe, I should have used rosetta tools' residue_renumber (that Riju and others contributed) instead as iNNterfaceDesign's Manual suggested? -> however, extracting rosetta_bin_linux_3.13_bundle.tgz (18 Gb) takes a long time. Rosetta_xxx.tgz used to be much smaller (around 3 Gb in 2011~2016 as I remember).

**Comment by rsyrlyb** [comment]
Hello,
renumbered 3ztj.pdb is attached. 
I did not try tools for renumbering other than clean_pdb.py, so I cannot tell if your suggestion works or not.
As far as I know, clean_pdb.py is in open access:
https://github.com/bestlab/GREMLIN_RF/blob/master/preprocessing/rosetta_scripts/clean_pdb.py
I hope this helps.
[3ztj_ABCDEF.pdb.gz](https://github.com/strauchlab/iNNterfaceDesign/files/8342212/3ztj_ABCDEF.pdb.gz)

**Comment by kimdn** [comment]
@rsyrlyb 
Thanks for sharing 3ztj_ABCDEF.pdb.gz

I just used

```
pdb: 3ztj_ABCDEF
anchor_res: 363-365,367
```
and ran
`python ../iNNterfaceDesign_scripts/1.preprocessing.py PepBB.input`

Then, I see
<img width="1413" alt="Screen Shot 2022-03-24 at 9 46 16 AM" src="https://user-images.githubusercontent.com/3903446/159967813-6a50dbd1-bcce-4d52-b040-af384ddf35d6.png">


What pyrosetta ver. did you use?

**Comment by kimdn** [comment]
The 2nd approach

I ran `python /people/kimd999/bin/rosetta_bin_linux_2021.16.61629_bundle/main/tools/protein_tools/scripts/clean_pdb.py 3ztj.pdb ignorechain
`

Then, I got
3ztj_ignorechain.pdb (that has ATOM only and starts with resnum=1)

Then, I ran the same command with
```
pdb: 3ztj_ignorechain
anchor_res: 363-365,367
```
Then, I got a similar error
<img width="1326" alt="Screen Shot 2022-03-24 at 9 56 03 AM" src="https://user-images.githubusercontent.com/3903446/159969531-43324d93-5bc0-4c73-a100-f058065aaa3b.png">

**Comment by rsyrlyb** [comment]
Hello,
the error is not related with pyrosetta this time.
It is related with your input file: the script got error while tried to read keywords.
I have run an input with your keywords and it runs smoothly.
Could you try to run my input file, I've attached it.

Raulia
________________________________

**Comment by kimdn** [comment]
For PepSep,,

I ran
`python ../iNNterfaceDesign_scripts/1.preprocessing_sp.py PepSep.input`

PepSep.input is
```
pdb: pdb_files/3ztj_ABCDEF
res1:363
```

Message is
<img width="1170" alt="Screen Shot 2022-03-24 at 10 13 26 AM" src="https://user-images.githubusercontent.com/3903446/159973086-db963e77-2838-4f4b-be25-a27dda1fd27a.png">

Using 3ztj_ignorechain resulted in the same/similar message as well.

**Comment by kimdn** [comment]
> Raulia

Hi Raulia,

Yes, the error message appears to be related to modules.functions.keywords rather than PyRosetta. I can't find your input file. If you mean your input file as [3ztj_ABCDEF.pdb.gz](https://github.com/strauchlab/iNNterfaceDesign/files/8342212/3ztj_ABCDEF.pdb.gz), I already tried it.

**Comment by rsyrlyb** [comment]
Names of files should not contain names of folders currently.
Besides, PepSep1 is for generating sequences for interfaces, but 3ztj_ABCDEF contains residues of target protein only.
You should provide ligand: HL chains which are native or backbones generated by PepBB.
res1 is first residue of ligand part, not target protein residue.

________________________________

**Comment by rsyrlyb** [comment]
I have attached it to the previous message. I am going to add a new reply in github with that input. 
Update: I was answering through email, that's why you did not see the input here.
________________________________

**Comment by rsyrlyb** [comment]
[input.txt](https://github.com/strauchlab/iNNterfaceDesign/files/8344027/input.txt)

**Comment by rsyrlyb** [comment]
Is input.txt work? Could you tell which difference between your and my input caused the error (if you got results)?

**Comment by kimdn** [comment]
Yes [input.txt](https://github.com/strauchlab/iNNterfaceDesign/files/8344027/input.txt) worked (generated 3ztj_ABCDEF/binders/,, pockets,,,). Thanks.

I was gonna share what caused the error anyway.

When I set PepBB.input
as
```
pdb: 3ztj_ABCDEF
#3ztj_ignorechain
#3ztj_ABCDEF failed as well
#3ztj_starts_w_1_by_pdb_tools.pdb failed with s-s

anchor_res: 363-365,367
```

it failed.

Once I removed # lines like you share input.txt, the error is solved.

**Comment by rsyrlyb** [comment]
Thanks.
Usage of # lines shouldn't cause the problem, such lines should be ignored:
text = {a.split(':')[0]: a.split(':')[1].strip() for a in text if **(a[0] != '#')** and (a.split(':')[1].strip() != '')}. 
However, empty line could. I'll check it.

**Comment by kimdn** [comment]
> Thanks. Usage of # lines shouldn't cause the problem, such lines should be ignored: text = {a.split(':')[0]: a.split(':')[1].strip() for a in text if **(a[0] != '#')** and (a.split(':')[1].strip() != '')}. However, empty line could. I'll check it.

Yes, input file that has # starting lines ran well.
