### ISSUE TITLE
Cannot open Manual.docx that was committed 3/27/2022

### ISSUE THREAD

**Issue by kimdn** [strauchlab/iNNterfaceDesign#5]
<img width="389" alt="Screen Shot 2022-03-28 at 1 40 48 PM" src="https://user-images.githubusercontent.com/3903446/160483527-543a46d6-4768-4c36-8b24-afb205832f71.png">

<img width="396" alt="Screen Shot 2022-03-28 at 1 40 54 PM" src="https://user-images.githubusercontent.com/3903446/160483535-fe0e3105-1980-4893-8555-02ea84fc48a1.png">

Can you upload pdf file instead?

**Comment by kimdn** [comment]
I could open Manual.docx directly from github repo.

However, I can't open Manual.docx that was downloaded by
`wget https://github.com/strauchlab/iNNterfaceDesign/blob/main/Manual.docx .`

**Comment by rsyrlyb** [comment]
I did not check Manual with the problem. But I replaced the file right now and successfully opened it after downloading using git. Could you attempt to open it again?

**Comment by kimdn** [comment]
Still opening Manual.docx 
after redownloading by
`wget https://github.com/strauchlab/iNNterfaceDesign/blob/main/Manual.docx .`
didn't work.

Since I can open Manual.docx by the other method, and I'm not an iNNterfaceDesign developer, I will close.
