### ISSUE TITLE
I'm not sure whether '4. Prediction of amino acid sequences.' works

### ISSUE THREAD

**Issue by kimdn** [strauchlab/iNNterfaceDesign#6]
Latest manual.docx says

`A file “prefix + _seqb.json” containing generated amino acid sequences for each binder is created.`

However, after my attempt of 4.amn_sampling.py,
I see that only '3ztj_ABCDEF_aas.json' is generated

```
[kimd999@deception01 run_iNNterfaceDesign]$ cat 3ztj_ABCDEF/3ztj_ABCDEF_aas.json
[["3ztj_ABCDEF_B363_0_0.pdb", ["PLTEIF"]], ["3ztj_ABCDEF_B364_0_0.pdb", ["DLLVVF"]], ["3ztj_ABCDEF_B365_0_0.pdb", ["GEIVPL"]], ["3ztj_ABCDEF_B367_0_0.pdb", ["RELVYN"]]]

```
Did I run correctly?
Or is this a document mismatch?

Another idea that I would do (if I'm the iNNterfaceDesign developer) is to add
simple conclusion remark (whether the operation ran well or not) after 4.amn_sampling.py runs.

This is a standard practice to help users.

Currently, I see only
```
...
2022-03-28 14:36:41.837029: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:717] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2022-03-28 14:36:41.845911: W tensorflow/core/common_runtime/process_function_library_runtime.cc:697] Ignoring multi-device function optimization failure: Invalid argument: The graph couldn't be sorted in topological order.

```

Thank you,

**Comment by rsyrlyb** [comment]
Your run is correct, it is a mistake in Manual. “prefix + _seqb.json” were outputs in early versions, after I renamed them to .._aas, but forgot to change Manual. Another mistake is found out thanks to you :).

**Comment by rsyrlyb** [comment]
["3ztj_ABCDEF_B363_0_0.pdb", ["PLTEIF"]: 
3ztj_ABCDEF_B363_0_0.pdb is a backbone in /binders_id/
PLTEIF - is a predicted aas for that backbone 
more sequences can be generated using 
"amn_design: 6" keyword

**Comment by kimdn** [comment]
```
["3ztj_ABCDEF_B363_0_0.pdb", ["PLTEIF"]:
3ztj_ABCDEF_B363_0_0.pdb is a backbone in /binders_id/
PLTEIF - is a predicted aas for that backbone
```

Ok, I see two '3ztj_ABCDEF_B363_0_0.pdb' e.g. in /binders/ folder and /complexes/ folder.
Which folder do you mean? 

In /binders_id/ folder, I do see '3ztj_ABCDEF_B363_0_0_id.pdb' only. There is no  '3ztj_ABCDEF_B363_0_0.pdb'

**Comment by rsyrlyb** [comment]
/binders/ contains binders generated by PepBB
/binders_id/ are binders from /binders/ idealized with Idealize() mover of pyrosetta. 
So, I meant 3ztj_ABCDEF_B363_0_0_id.pdb. 
Mapping of predicted aas from .._aas file and relaxation have to be conducted using 3ztj_ABCDEF_B363_0_0_id.pdb of course.
But names in ..._aas do mot have "_id" currently. Maybe I have to rewrite code to avoid confusion
/complexes/ contains complexes with binders from /binders_id/ and also can be used for mapping/relaxation

**Comment by kimdn** [comment]
OK, I see.

I also saw that pdb files in /complex/ folder have original/starting AA (poly glycine) only.

It appears that either 

- users need to replace AA from 3ztj_ABCDEF_aas.json to 3ztj_ABCDEF_B363_0_0_complex.pdb (there should be a corresponding function in PyRosetta?) and run FastRelax
- or iNNterfaceDesign needs further development to automate this process.

**Comment by kimdn** [comment]
> ["3ztj_ABCDEF_B363_0_0.pdb", ["PLTEIF"]: 3ztj_ABCDEF_B363_0_0.pdb is a backbone in /binders_id/ PLTEIF - is a predicted aas for that backbone more sequences can be generated using "amn_design: 6" keyword

Yes, I just added 
`amn_design: 6`

Then, it generated 6 designs each.

Before this running, I mis-thought that 
amn_design: 1
is to design 1 AA

and
amn_design: 6
is to design 6 AAs

**Comment by rsyrlyb** [comment]
Maximum possible number of aas for 1 anchor residue is 1944 (324 possible backbones x 6 aas for each) if binding site allows it and all maximizing options are used

**Comment by kimdn** [comment]
What are maximizing options?
max_pos and max_sst?

Why 324 possible bb (yes, I know rosetta people use bb for backbone and sc for sidechain) s?

**Comment by rsyrlyb** [comment]
max_pos, max_sst and threshold probabilities
We are going to publish PepBB paper during this week. It will have details about the method
